# Sudoku Solver

# Modelling

Before answering directly the questions regarding the formulation of the problem, we will present a model of a $n^2 \times n^2$ Sudoku game. For brevity, we will call a Sudoku with a grid of dimensions $n^2 \times n^2$ a n-size grid.

Let's start by analyzing a simple solved game, for exemple, the 2-size sudoku given in the exercise description. Notice 

|   	|   	|   	|   	|
|---	|---	|---	|---	|
|   	| 2 	| 4 	|   	|
|   	|   	|   	| 2 	|
| 3 	|   	|   	|   	|
|   	| 1 	| 3 	|   	|


We can then solve this example quite easily ourselves.


|   	|   	|   	|   	|
|---	|---	|---	|---	|
| 1  	| 2 	| 4 	| 3  	|
| 4  	| 3  	| 1  	| 2 	|
| 3 	| 4  	| 2  	| 1  	|
| 2  	| 1 	| 3 	| 4  	|

However, notice the representation of the final Sudoku. We have a 4x4 squares each which can have 4 possible values (1, 2, 3 or 4). Generalizing, for a n-size sudoku, we have a $n^2 \times n^2$ matrix with $n^2$ possible values inside of it.

While this representation is interesting, it does not provide greater insights in how can we establish our constraints. However, knowing that we have a finite space for the numbers in our grid, we might be compelled into splitting this grid into n separate grids, one for each number.

|   	|   k	|  = 	|  1 	|  
|---	|---	|---	|---	| 
| 1  	|   	|   	|    	| 
|   	|   	| 1  	|   	|
|   	|   	|   	| 1  	| 
|    	| 1 	|   	|   	| 

|   	|   k	|  = 	|   2	|
|---	|---	|---	|---	|
|   	| 2  	|   	|    	|
|   	|   	|   	| 2  	|
|   	|   	| 2  	|   	|
| 2   	|   	|   	|   	|


|   	|   k	|  = 	|  3 	|
|---	|---	|---	|---	|
|   	|   	|   	| 3  	|
|   	| 3  	|   	|   	|
| 3 	|   	|   	|    	|
|   	|   	| 3 	|   	|


|   	|  k 	| =  	|  4 	|
|---	|---	|---	|---	|
|   	|   	| 4 	|   	|
| 4  	|   	|   	|   	|
|   	| 4  	|   	|   	|
|   	|   	|   	| 4  	|

In fact, this representation is convenient since we know that there will be only a given number inside of each matrix. Therefore, each of these matrixes can be represented as a binary. (Consider the empty spaces as 0 values, they were left empty only for clarity).

|   	|   k	|  = 	|  1 	|  
|---	|---	|---	|---	| 
| 1  	|   	|   	|    	| 
|   	|   	| 1  	|   	|
|   	|   	|   	| 1  	| 
|    	| 1 	|   	|   	| 

|   	|   k	|  = 	|   2	|
|---	|---	|---	|---	|
|   	| 1  	|   	|    	|
|   	|   	|   	| 1  	|
|   	|   	| 1  	|   	|
| 1   	|   	|   	|   	|


|   	|   k	|  = 	|  3 	|
|---	|---	|---	|---	|
|   	|   	|   	| 1  	|
|   	| 1  	|   	|   	|
| 1 	|   	|   	|    	|
|   	|   	| 1 	|   	|


|   	|  k 	| =  	|  4 	|
|---	|---	|---	|---	|
|   	|   	| 1 	|   	|
| 1  	|   	|   	|   	|
|   	| 1  	|   	|   	|
|   	|   	|   	| 1  	|

Now we have a representation that is isomorphic for all numbers. This means that if we can represent a constraint (a rule) in this binary matrix format, it will generalize for every single number in the game. For example, we know that in Sudoku we cannot have two of the same number in a column. This means that a configuration such as.


| For  	|  any 	| k  	|   	|
|---	|---	|---	|---	|
| 1  	|   	| 1 	|   	|
| 1  	|   	|   	|   	|
|   	| 1  	|   	|   	|
|   	|   	|   	| 1  	|

Is impossible.

Therefore, how can we generalize this rule? On this case, we only need to add the values for all of the columns in our binary matrix. This value **must be equal** to 1, since we have one and only one of each number in a matrix column.

Before formally defining these constraints, let's attempt to find the intuition behind it and all the other rules. Once we have this intuition, the formalization will be much easier to define.

* **Rule 1: The sums of the columns for every binary matrix must be equal to one.**

In short, for every column in every binary matrix.

Visualization for one column:

| For  	|  any 	| k  	|   	|
|---	|---	|---	|---	|
| $x_1$  	|   	|   	|   	|
| $x_2$  	|   	|   	|   	|
| $x_3$  	|    	|   	|   	|
| $x_4$  	|   	|   	|   	|

We have that $\sum x_i = 1 \hspace{0.3cm} \forall i$.

An analogous process is done for the rows, each row must add to one in every binary matrix.

* **Rule 2: The sums of the rows for every binary matrix must be equal to one.**
For every row in every binary matrix.

Visualization for one row:

| For  	|  any 	| k  	|   	|
|---	|---	|---	|---	|
| $x_1$  	|  $x_2$ 	|  $x_3$  	|  $x_4$ 	|
| &nbsp; 	|   	|   	|   	|
| &nbsp;	|    	|   	|   	|
|  &nbsp; 	|   	|   	|   	|

We have that $\sum x_i = 1 \hspace{0.3cm} \forall i$.

Likewise, sudoku provides restrictions of having two of the same number in every $n \times n$ subsquare of our grid.

* **Rule 3: The sums of the subsquares for every binary matrix must be equal to one.**
For every subsquare in every binary matrix.

Visualization for one subsquare:

| For  	|  any 	| k  	|   	|
|---	|---	|---	|---	|
| $x_1$  	|  $x_2$ 	| &nbsp;   	| &nbsp; 	|
| $x_3$ 	|  $x_4$ 	|   	|   	|
| &nbsp;	|    	|   	|   	|
|  &nbsp; 	|   	|   	|   	|

We have that $\sum x_i = 1 \hspace{0.3cm} \forall i$.


* **Rule 4: We must only have a single number per square** 

Notice, however, that these constraints are not sufficient in order to fully describe our sudoku problem. We need a single extra constraint, this time between different binary matrices. Even if we described all the rules for each number, we haven't yet restricted the fact that we can only have a single number for each slot in our original grid. 

Thankfully, doing so is trivial using a similar process we have used so far, all we need to ensure is that for all i, j where i and j are indexes of our original grid, the sum of all binary matrices in i, j is equal to 1.

For every slot in our grid.

Visualization

|   	|   k	|  = 	|  1 	|  
|---	|---	|---	|---	| 
| $x_1$  	|   	|   	|    	| 
|   	|   	|   	|   	|
|   	|   	|   	|   	| 
|    	|  	|   	|   	| 

|   	|   k	|  = 	|  2 	|  
|---	|---	|---	|---	| 
| $x_2$  	|   	|   	|    	| 
|   	|   	|   	|   	|
|   	|   	|   	|   	| 
|    	|  	|   	|   	| 

|   	|   k	|  = 	|  1 	|  
|---	|---	|---	|---	| 
| $x_3$  	|   	|   	|    	| 
|   	|   	|   	|   	|
|   	|   	|   	|   	| 
|    	|  	|   	|   	| 

|   	|   k	|  = 	|  1 	|  
|---	|---	|---	|---	| 
| $x_4$  	|   	|   	|    	| 
|   	|   	|   	|   	|
|   	|   	|   	|   	| 
|    	|  	|   	|   	| 


We have that $\sum x_i = 1 \hspace{0.3cm} \forall i$.
 

With these intuitions, we can formalize the previous concepts algebrically with a $$n^2 \times n^2 \times n^2$$ 3D binary matrix $M_{ijk}$ where $i, j$ are the coordinates in the original grid and $k$ represents a given number from our response state.

Note that we don't have a cost function since any feasible basis provides a solution to our sudoku.

We can formalize this problem as finding a feasible basis solution for the given constraints. 

$$\sum_I x_{ijk} = 1 \hspace{0.4cm} \forall j, k \in [1, 2, ..., n^2] $$
$$\sum_J x_{ijk} = 1 \hspace{0.4cm} \forall i, k \in [1, 2, ..., n^2]$$
$$\sum_K x_{ijk} = 1 \hspace{0.4cm} \forall i, j \in [1, 2, ..., n^2]$$
$$\sum_{S} x_{ijk} = 1 \hspace{0.4cm} $$

Where I, J, K and S are the spaces for rows $[1, 2, ..., n^2]$, columns $[1, 2, ..., n^2]$, numbers $[1, 2, ..., n^2]$, and subsquares specifically.

Note: Indexing S

A subsquare is a $n x n$ square of our original matrix. We can index it by having a origin of subsquare, and then spanning all the combinations of n steps to the right and n steps down from the origin. Notice since it is %n \times n$, we only have $n$ subsquares.

For example, in a 2-size matrix, we will have 2x2 subsquares.

Starting at $(1,1)$, we span right and down in order to create a 2x2 matrix.

$$(1,1), (1,2), (2,1), (2,2)$$

We have fully spanned a single subsquare, however we need to move foward to another starting point. In order to do so, we move from our original starting point by adding n (in our case, 2). We can add n to our (1,1) until we exaust all possible starting points.

Starting points:
$$(1,1), (1,3), (3,1), (3,3)$$

Finally, we can nest both of these processes in order to index every single subsquare.

$$i = 1 + x \cdot n + z$$

$$j = 1 + y \cdot n + w$$

Where x and y are positive integers where $x \cdot n \leq n^2$ and $y \cdot n \leq n^2$.

Where w and z are positive integers where $w < n$ and $z < n$.

To find a subsquare, we fix x and y and iterate over all w and z.

* **Enconding the given values of the sudoku problem**

This configuration then gives us a very intuitive way to plug in the values of the specific sudoku that we want to solve. It suffices to state that for every number $k$ in our problem:

$$x_{ijk} = 1$$

# 1.1 Formulation

To formulate the problem, propose answers to the following questions :

**— Using only binary variables, how can we specify that a given number k is located in
position (i, j) in the grid ?**

Ans: We can solve this by acessing directly $x_{ijk}$. If this value returns 1, the number is located in that position of the grid. We can iterate by every number to see the value of (i, j) and return the given number 

**— What variables should we use ?**

Ans: We use binary variables in our 3D $n^2 \times n^2 \times n^2$ matrix.

**— How do we express the line, column and square constraints ?**

Ans: See explanation above for further details. In short:
We can formalize this problem as finding a feasible basis solution for the given constraints. 

$$\sum_I x_{ijk} = 1 \hspace{0.4cm} \forall j, k \in [1, 2, ..., n^2] $$
$$\sum_J x_{ijk} = 1 \hspace{0.4cm} \forall i, k \in [1, 2, ..., n^2]$$
$$\sum_{S} x_{ijk} = 1 \hspace{0.4cm} $$

Where I, J, and S are the spaces for rows $[1, 2, ..., n^2]$, columns $[1, 2, ..., n^2]$, and subsquares specifically.

For subsquares: 

$$i = 1 + x \cdot n + z$$

$$j = 1 + y \cdot n + w$$

Where x and y are positive integers where $xn \leq n^2$ and $yn \leq n^2$.

Where w and z are positive integers where $w < n$ and $z < n$.

To find a subsquare, we fix x and y and iterate over all w and z.

**— How do we express the fact that only a single number can be located at any location
(i, j) ?**

Ans: See explanation above for further details. In short:

$$\sum_K x_{ijk} = 1 \hspace{0.4cm} \forall i, j \in [1, 2, ..., n^2]$$

Where K is the space for individual numbers $[1, 2, ..., n^2]$

**— How do we express the known numbers as constraints ?**

Ans: For every known number, we set $x_{ijk} = 1$ as an additional constraint.

# Sudoku Implementation

In [45]:
%matplotlib notebook
import numpy as np
import cvxopt
import cvxopt.glpk
from cvxopt import matrix

In [46]:
## To help create the huge matrix
def unravel(i,j,k,size=3):
    '''
    Associate a unique variable index given a 3-index (ijk) 
    '''
    n2 = size*size
    assert(i>=0 and i<n2)
    assert(j>=0 and i<n2)
    assert(k>=0 and i<n2)
    
    return(k+ j*n2+ i*n2*n2)

In [93]:
# Size is the size of our sudoku, K is the the matrix containing the fixed numbers for our game
def sudoku_constraints(size, K):
    n2=size*size
    
    # Creating the constraint matrix
    A=np.zeros((4*n2*n2,n2*n2*n2))
    
    ## Here I give the line constraints
    ## line constraints: only one number per line
    c=0
    for k in range(n2): ## for all numbers
        for j in range(n2): ## for all columns
            for i in range(n2): # for all rows
                A[c,unravel(i,j,k, size=size)] = 1 ## only one number k on line i
            c += 1

    for k in range(n2): ## for all numbers
        for i in range(n2): ## for all rows
            for j in range(n2): # for all columns
                A[c,unravel(i,j,k, size=size)] = 1 ## only one number k on line i
            c += 1        


    for i in range(n2): ## for all rows
        for j in range(n2): # for all columns
            for k in range(n2): ## for all numbers
                A[c,unravel(i,j,k, size=size)] = 1 ## only one number k on line i
            c += 1


    # For k, make so that each of the squares is valid
    # For a size 2 matrix, we have a 2x2 small squares, as such
    # # 1 # #
    # # 1 # #
    #1 1 1 1 1 
    # # 1 # # 
    # # 1 # #
    # For a size n matrix, we have nxn small squares
    # Each small square has size nxn
    for k in range(n2):
        for largesquare_i in range(size):
            for largesquare_j in range(size):
                for increment_i in range(size):
                    for increment_j in range(size):
                        i = largesquare_i * size + increment_i
                        j = largesquare_j * size + increment_j
                        A[c,unravel(i,j,k, size=size)] = 1
                c += 1
    # So far, we established the base rules for every sudoku game
    
    # Adding the constraints from the matrix values
    for i in range(n2):
        for j in range(n2):
            k = K[i,j]
            if (k>0):
                newrow=np.zeros(n2*n2*n2)
                newrow[unravel(i,j,k-1,size=size)]=1
                A=np.vstack((A,newrow))
    
    return A

# Returns a solution to the Optimization problem
def solve_constraints(A):
    b=matrix(np.ones(A.shape[0])) ## set partition
    c=matrix(np.zeros(A.shape[1])) ## zero cost
    G=matrix(np.zeros(A.shape))
    h=matrix(np.zeros(A.shape[0]))
    binary=np.array(range(A.shape[1]))
    I=set(binary)
    B=set(range(A.shape[1]))
    Aeq = matrix(A)

    (status, solution) = cvxopt.glpk.ilp(c=c,G=G,h=h,A=Aeq,b=b,B=set(range(A.shape[1])))
    
    return solution

# Formats the cvxopt representation of the solution to a Suoku representation
def format_solution(size, solution):
    n2= size*size
    
    ans = np.zeros((n2,n2))

    for i in range(n2):
        for j in range(n2):
            for k in range(n2):
                if solution[unravel(i,j,k, size=size)] != 0:
                    ans[i][j] = k + 1

    return ans

# Solves the sudoku specified by the matrix K where K is a n^2 x n^2 matrix
# Empty squares (that will be filled) must be equal to 0
# Non-empty squares must be integers in range [1, 2, ..., n^2]
def solve_sudoku(K):
    size = int(np.sqrt(len(K)))
    
    A = sudoku_constraints(size, K)
    solution = solve_constraints(A)
    return format_solution(size, solution)

# Example

In [94]:
K = np.array([
 [0,2, 4,0],
 [0,0, 0,2],
 
 [3,0, 0,0],
 [0,1, 3,0]])

print(solve_sudoku(K))

[[1. 2. 4. 3.]
 [4. 3. 1. 2.]
 [3. 4. 2. 1.]
 [2. 1. 3. 4.]]


# Simple

In [95]:
K = np.array([
 [0,8,0, 9,0,1, 0,5,0],
 [0,0,2, 6,8,7, 3,0,0],
 [0,0,3, 0,0,0, 6,0,0],
    
 [3,9,0, 0,0,0, 0,6,5],
 [6,0,0, 4,7,5, 0,0,3],
 [5,7,0, 0,0,0, 0,8,4],
    
 [0,0,9, 0,0,0, 8,0,0],
 [0,0,5, 1,2,4, 9,0,0],
 [0,4,0, 8,0,3, 0,2,0]])


print(solve_sudoku(K))

[[7. 8. 6. 9. 3. 1. 4. 5. 2.]
 [4. 5. 2. 6. 8. 7. 3. 1. 9.]
 [9. 1. 3. 5. 4. 2. 6. 7. 8.]
 [3. 9. 4. 2. 1. 8. 7. 6. 5.]
 [6. 2. 8. 4. 7. 5. 1. 9. 3.]
 [5. 7. 1. 3. 6. 9. 2. 8. 4.]
 [2. 3. 9. 7. 5. 6. 8. 4. 1.]
 [8. 6. 5. 1. 2. 4. 9. 3. 7.]
 [1. 4. 7. 8. 9. 3. 5. 2. 6.]]


# Very Hard

In [96]:
K = np.array([
 [7,0,0, 0,0,0, 4,0,0],
 [0,2,0, 0,7,0, 0,8,0],
 [0,0,3, 0,0,8, 0,0,9],
    
 [0,0,0, 5,0,0, 3,0,0],
 [0,6,0, 0,2,0, 0,9,0],
 [0,0,1, 0,0,7, 0,0,6],
    
 [0,0,0, 3,0,0, 9,0,0],
 [0,3,0, 0,4,0, 0,6,0],
 [0,0,9, 0,0,1, 0,0,5]])


print(solve_sudoku(K))

[[7. 9. 8. 6. 3. 5. 4. 2. 1.]
 [1. 2. 6. 9. 7. 4. 5. 8. 3.]
 [4. 5. 3. 2. 1. 8. 6. 7. 9.]
 [9. 7. 2. 5. 8. 6. 3. 1. 4.]
 [5. 6. 4. 1. 2. 3. 8. 9. 7.]
 [3. 8. 1. 4. 9. 7. 2. 5. 6.]
 [6. 1. 7. 3. 5. 2. 9. 4. 8.]
 [8. 3. 5. 7. 4. 9. 1. 6. 2.]
 [2. 4. 9. 8. 6. 1. 7. 3. 5.]]


# Special version for computer scientists

We need to format this matrix from the hexadecimal representation to a numeric representation.

Also note that this matrix starts at 0 (it is for computer scientists after all). We will also need to increment 1 to every number.

In order to do this, we will use a dictionary as a map.

In [98]:
K = np.array([
       [8, 'F', 'X', 'C',    'X', 'X', 'X', 'X',    'X', 'A', 'X','X',   'X', 'X', 'X', 6],
       ['X', 'X', 'X', 'A',  'X', 'X', 'X', 'F',    'X', 'X', 'X','B',   7, 4, 'D', 'X'],
       ['B', 'X', 4, 'X',    'X', 'X', 'D', 6,      'X', 7, 'X', 'X',    0, 'X', 5, 'X'],
       [1, 'X', 'X', 'X',    'X', 'X', 'X', 0,       3,'X', 9, 2,        'X', 'X', 'X', 'X'],
       
       ['X', 'X', 'X', 'X',       'X', 1, 'F', 'D',       'X', 3, 0, 'X',        'X', 'E', 7, 4],
       ['X', 1, 'X', 6,            'X', 'X', 'X', 'C',    'X', 'B', 'X', 'X',    'A', 'X', 3, 'X'],
       ['X', 'C', 'X', 'D',        'X', 'X', 6, 3,        'X', 5, 'X', 'X',      9, 2, 'X', 'X'],
       [9, 'X', 3, 4,              'E', 'X', 2, 'X',     'X', 'X', 7, 'D',      'X', 'X', 'X', 'X'],
       
       ['X', 'X', 'X', 'X',         5, 7, 'X', 'X',       'X', 8, 'X', 'C',       3, 0, 'X', 'A'],
       ['X', 'X', 'E', 2,          'X', 'X', 4, 'X',      7, 1, 'X', 'X',        'F', 'X', 6, 'X'],
       ['X', 5, 'X', 3,            'X', 'X', 8, 'X',     9, 'X', 'X', 'X',      'E', 'X', 'C', 'X'],
       [7, 0, 6, 'X',              'X', 'C', 9, 'X',      'D', 'E', 3, 'X',      'X', 'X', 'X', 'X'],
       
       ['X', 'X', 'X', 'X', 'D', 'E', 'X', 4, 0, 'X', 'X', 'X', 'X', 'X', 'X', 2],
       ['X', 7, 'X', 8, 'X', 'X', 'C', 'X', 4, 2, 'X', 'X', 'X', 'B', 'X', 5],
       ['X', 2, 9, 'E', 'B', 'X', 'X', 'X', 5, 'X', 'X', 'X', 4, 'X', 'X', 'X'],
       [6, 'X', 'X', 'X', 'X', 'X', 7, 'X', 'X', 'X', 'X', 'X', 1, 'X', 8, 3]], dtype=object)

transform_dict = {'X': 0,
                    0: 1, 1:2, 2:3, 3:4, 4:5, 5:6, 6:7, 7:8, 8:9, 9:10,
                  'A': 11, 'B':12, 'C':13, 'D':14, 'E':15, 'F':16}

K = np.vectorize(transform_dict.get)(K)

print(K)

[[ 9 16  0 13  0  0  0  0  0 11  0  0  0  0  0  7]
 [ 0  0  0 11  0  0  0 16  0  0  0 12  8  5 14  0]
 [12  0  5  0  0  0 14  7  0  8  0  0  1  0  6  0]
 [ 2  0  0  0  0  0  0  1  4  0 10  3  0  0  0  0]
 [ 0  0  0  0  0  2 16 14  0  4  1  0  0 15  8  5]
 [ 0  2  0  7  0  0  0 13  0 12  0  0 11  0  4  0]
 [ 0 13  0 14  0  0  7  4  0  6  0  0 10  3  0  0]
 [10  0  4  5 15  0  3  0  0  0  8 14  0  0  0  0]
 [ 0  0  0  0  6  8  0  0  0  9  0 13  4  1  0 11]
 [ 0  0 15  3  0  0  5  0  8  2  0  0 16  0  7  0]
 [ 0  6  0  4  0  0  9  0 10  0  0  0 15  0 13  0]
 [ 8  1  7  0  0 13 10  0 14 15  4  0  0  0  0  0]
 [ 0  0  0  0 14 15  0  5  1  0  0  0  0  0  0  3]
 [ 0  8  0  9  0  0 13  0  5  3  0  0  0 12  0  6]
 [ 0  3 10 15 12  0  0  0  6  0  0  0  5  0  0  0]
 [ 7  0  0  0  0  0  8  0  0  0  0  0  2  0  9  4]]


Now we have a solution from [1, 2, ..., 16].

In [121]:
solved_numerical = solve_sudoku(K)
print(solved_numerical)

[[ 9. 16.  1. 13.  2. 12.  6.  8. 15. 11. 14.  5.  3.  4. 10.  7.]
 [ 4.  7.  3. 11.  9. 10. 15. 16.  2.  1.  6. 12.  8.  5. 14. 13.]
 [12. 15.  5. 10.  3.  4. 14.  7. 16.  8. 13.  9.  1. 11.  6.  2.]
 [ 2. 14.  6.  8. 13.  5. 11.  1.  4.  7. 10.  3. 12.  9. 16. 15.]
 [ 3. 12.  9.  6. 10.  2. 16. 14. 11.  4.  1.  7. 13. 15.  8.  5.]
 [15.  2. 16.  7.  8.  9.  1. 13.  3. 12.  5. 10. 11.  6.  4. 14.]
 [ 1. 13.  8. 14.  5. 11.  7.  4.  9.  6.  2. 15. 10.  3. 12. 16.]
 [10. 11.  4.  5. 15.  6.  3. 12. 13. 16.  8. 14.  9.  7.  2.  1.]
 [ 5. 10. 14.  2.  6.  8. 12. 15.  7.  9. 16. 13.  4.  1.  3. 11.]
 [13.  9. 15.  3.  4.  1.  5. 11.  8.  2. 12.  6. 16. 14.  7. 10.]
 [16.  6. 11.  4.  7. 14.  9.  2. 10.  5.  3.  1. 15.  8. 13. 12.]
 [ 8.  1.  7. 12. 16. 13. 10.  3. 14. 15.  4. 11.  6.  2.  5.  9.]
 [ 6.  4. 12. 16. 14. 15.  2.  5.  1. 10.  9.  8.  7. 13. 11.  3.]
 [11.  8.  2.  9.  1. 16. 13. 10.  5.  3.  7.  4. 14. 12. 15.  6.]
 [14.  3. 10. 15. 12.  7.  4.  9.  6. 13. 11.  2.  5. 16.  1. 

Finally, we reformat this matrix back to the original representation using hexadecimal.

In [122]:
inv_transform = {v: k for k, v in transform_dict.items()}

print(inv_transform)

{0: 'X', 1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9, 11: 'A', 12: 'B', 13: 'C', 14: 'D', 15: 'E', 16: 'F'}


In [123]:
solved_hex = [list(map(inv_transform.get, list(array))) for array in solved_numerical]

for line in solved_hex:
    print(line)

[8, 'F', 0, 'C', 1, 'B', 5, 7, 'E', 'A', 'D', 4, 2, 3, 9, 6]
[3, 6, 2, 'A', 8, 9, 'E', 'F', 1, 0, 5, 'B', 7, 4, 'D', 'C']
['B', 'E', 4, 9, 2, 3, 'D', 6, 'F', 7, 'C', 8, 0, 'A', 5, 1]
[1, 'D', 5, 7, 'C', 4, 'A', 0, 3, 6, 9, 2, 'B', 8, 'F', 'E']
[2, 'B', 8, 5, 9, 1, 'F', 'D', 'A', 3, 0, 6, 'C', 'E', 7, 4]
['E', 1, 'F', 6, 7, 8, 0, 'C', 2, 'B', 4, 9, 'A', 5, 3, 'D']
[0, 'C', 7, 'D', 4, 'A', 6, 3, 8, 5, 1, 'E', 9, 2, 'B', 'F']
[9, 'A', 3, 4, 'E', 5, 2, 'B', 'C', 'F', 7, 'D', 8, 6, 1, 0]
[4, 9, 'D', 1, 5, 7, 'B', 'E', 6, 8, 'F', 'C', 3, 0, 2, 'A']
['C', 8, 'E', 2, 3, 0, 4, 'A', 7, 1, 'B', 5, 'F', 'D', 6, 9]
['F', 5, 'A', 3, 6, 'D', 8, 1, 9, 4, 2, 0, 'E', 7, 'C', 'B']
[7, 0, 6, 'B', 'F', 'C', 9, 2, 'D', 'E', 3, 'A', 5, 1, 4, 8]
[5, 3, 'B', 'F', 'D', 'E', 1, 4, 0, 9, 8, 7, 6, 'C', 'A', 2]
['A', 7, 1, 8, 0, 'F', 'C', 9, 4, 2, 6, 3, 'D', 'B', 'E', 5]
['D', 2, 9, 'E', 'B', 6, 3, 8, 5, 'C', 'A', 1, 4, 'F', 0, 7]
[6, 4, 'C', 0, 'A', 2, 7, 5, 'B', 'D', 'E', 'F', 1, 9, 8, 3]
